### ISSUE TITLE
Build #70 fails

### ISSUE THREAD

**Issue by kangwonlee** [autodrive/python-control#1]
* Build [#70](https://travis-ci.org/kangwonlee/python-control/builds/464732118) (8f57e48692b70865d278b74f1e778ef1d2ed1f45) fails

|      | OS | `python` | `scipy` | `slycot` |
|-----|-----|-----------------------|-----------|----------|
| &#10004; | `linux` | * | * | * |
| &#10005; | `osx` | 3.6 | `scipy` | Y |
| &#10004; | `osx` | 3.6 | `scipy` | N |
| &#10004; | `osx` | 3.6 | `0.19.1` | N |
| &#10005; | `osx` | 3.5 | `scipy` | Y |
| &#10004; | `osx` | 3.5 | `scipy` | N |
| &#10004; | `osx` | 3.5 | `0.19.1` | N |
| &#10005; | `osx` | 2.7 | `scipy` | Y |
| &#10004; | `osx` | 2.7 | `scipy` | N |
| &#10004; | `osx` | 2.7 | `0.19.1` | N |

* Tests on `osx`, with `slycot` fails

**Comment by kangwonlee** [comment]
* Build [#71](https://travis-ci.org/kangwonlee/python-control/builds/465285816) mostly passes but not a tree

|      | OS | `python` | `scipy` | `slycot` |
|-----|-----|-----------------------|-----------|----------|
| &#10005; | `linux` | 3.6 | `scipy` | Y |
| &#10004; | `linux` | 3.6 | `scipy` | N |
| &#10004; | `linux` | 3.6 | `0.19.1` | N |
| &#10004; | `linux` | 3.5 | `scipy` | Y |
| &#10004; | `linux` | 3.5 | `scipy` | N |
| &#10004; | `linux` | 3.5 | `0.19.1` | N |
| &#10004; | `linux` | 2.7 | `scipy` | Y |
| &#10004; | `linux` | 2.7 | `scipy` | N |
| &#10004; | `linux` | 2.7 | `0.19.1` | N |

**Comment by kangwonlee** [comment]
* Build [#74](https://travis-ci.org/kangwonlee/python-control/builds/465340671) mostly passes

|      | OS | `python` | `scipy` | `slycot` |
|-----|-----|-----------------------|-----------|----------|
| &#10004; | `linux` | 3.6 | `scipy` | Y |
| &#10005; | `linux` | 3.5 | `scipy` | Y |
| &#10004; | `linux` | 2.7 | `scipy` | Y |
| &#10004; | `linux` | 3.6 | `scipy` | N |
| &#10004; | `linux` | 3.5 | `scipy` | N |
| &#10004; | `linux` | 2.7 | `scipy` | N |
| &#10004; | `linux` | 3.6 | `0.19.1` | N |
| &#10004; | `linux` | 3.5 | `0.19.1` | N |
| &#10004; | `linux` | 2.7 | `0.19.1` | N |

```
======================================================================
ERROR: testLQR (control.tests.matlab_test.TestMatlab)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/kangwonlee/python-control/control/tests/matlab_test.py", line 418, in testLQR
    np.eye(1), [[1.0], [1.0], [2.0]])
  File "/home/travis/build/kangwonlee/python-control/control/statefbk.py", line 325, in lqr
    X,rcond,w,S,U,A_inv = sb02md(nstates, A_b, G, Q_b, 'C')
  File "/home/travis/miniconda/envs/test-environment/lib/python3.5/site-packages/slycot/synthesis.py", line 350, in sb02md
    raise e
ValueError: the Hamiltonian or symplectic matrix H has less than n stable eigenvalues
----------------------------------------------------------------------
```
